import Card from "@/components/Card";
import Tabs from "@/components/Tabs";
import { User } from "@prisma/client";
import Head from "next/head";
import Script from "next/script";
import { useEffect, useState } from "react";
import prisma from "@/lib/prisma";

export async function getServerSideProps() {
  try {
    const user: User | null = await prisma.user.findFirst();

    if (user) {
      return {
        props: {
          user,
        },
      };
    }
    return {
      props: {},
    };
  } catch (err: any) {
    console.error(err);
  }
}

type Props = {
  user: User;
};

export default function Home({ user }: Props) {
  console.log("user in home: ", user);
  // const [currentUser, setCurrentUser] = useState<User | null>(null);

  // console.log("current user: ", currentUser);

  // useEffect(() => {
  //   const getCurrentUser = async (): Promise<{ data: User }> => {
  //     const response = await fetch("api/user");
  //     const data = await response.json();
  //     setCurrentUser(data);
  //     return data;
  //   };

  //   getCurrentUser();
  // }, []);

  return (
    <div>
      <Head>
        <title>DM- App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen flex-col bg-gradient-to-b from-gray-900 to-slate-800 text-white">
        <header className="py-16">
          <h1 className="mb-6 text-center text-5xl font-bold">My DMz</h1>
        </header>

        <main className="flex-1">
          <section className="flex justify-center">
            <div>
              <Tabs
                labels={["All", "Accepted"]}
                className="mb-6 flex justify-center"
              />
              <Card />
            </div>
          </section>
        </main>

        <footer className="border-t border-gray-800 px-8 py-12">
          <div className="px-8 text-center font-medium">
            <a href="https://github.com/andrejjurkin/create-tw">
              Create Tailwind
            </a>
          </div>
        </footer>
      </div>
      {/* <Script src="https://buttons.github.io/buttons.js" /> */}
    </div>
  );
}
