import Card from "@/components/Card";
import Tabs from "@/components/Tabs";
import Head from "next/head";
import Script from "next/script";

export default function Home() {
  return (
    <div>
      <Head>
        <title>DM- App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen flex-col bg-gradient-to-b from-gray-900 to-slate-800 text-white">
        <header className="py-16">
          <h1 className="mb-6 text-center text-5xl font-bold">My DMz</h1>
        </header>

        <main className="flex-1">
          <section className="flex justify-center">
            <div>
              <Tabs
                labels={["All", "Accepted"]}
                className="mb-6 flex justify-center"
              />
              <Card />
            </div>
          </section>
        </main>

        <footer className="border-t border-gray-800 px-8 py-12">
          <div className="px-8 text-center font-medium">
            <a href="https://github.com/andrejjurkin/create-tw">
              Create Tailwind
            </a>
          </div>
        </footer>
      </div>
      {/* <Script src="https://buttons.github.io/buttons.js" /> */}
    </div>
  );
}
